const imageFor = (seed) => `https://images.unsplash.com/${seed}?auto=format&fit=crop&w=500&q=80`;

export const brands = [
  {
    id: "voltedge",
    name: "VoltEdge",
    headingFont: "Inter",
    bodyFont: "Inter",
    colors: ["#0c7c78", "#d9a62e", "#c45457", "#17211f"],
    logo:
      "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='220' height='90' viewBox='0 0 220 90'%3E%3Crect width='220' height='90' rx='12' fill='%23ffffff'/%3E%3Cpath d='M32 66 58 16h35L75 46h30L58 76l16-30H47Z' fill='%23d9a62e'/%3E%3Ctext x='112' y='41' font-family='Arial' font-size='22' font-weight='700' fill='%230c7c78'%3EVolt%3C/text%3E%3Ctext x='112' y='65' font-family='Arial' font-size='22' font-weight='700' fill='%2317211f'%3EEdge%3C/text%3E%3C/svg%3E",
  },
];

export const products = [
  {
    id: "VE-4100",
    name: "PulseGuard Inverter",
    category: "Power Control",
    thumbnail: imageFor("photo-1581092160562-40aa08e78837"),
    attributes: {
      productId: "VE-4100",
      productName: "PulseGuard Inverter",
      category: "Power Control",
      description: "Compact inverter platform for protected industrial control cabinets and field units.",
      voltage: "480V",
      enclosure: "IP66 aluminum",
      operatingTemp: "-20C to 55C",
      warranty: "5 years",
    },
    assets: {
      heroImage: imageFor("photo-1518770660439-4636190af475"),
      detailImage: imageFor("photo-1581092334651-ddf26d9a09d0"),
    },
  },
  {
    id: "AQ-220",
    name: "AquaSense Flow Meter",
    category: "Fluid Monitoring",
    thumbnail: imageFor("photo-1581093588401-fbb62a02f120"),
    attributes: {
      productId: "AQ-220",
      productName: "AquaSense Flow Meter",
      category: "Fluid Monitoring",
      description: "Inline ultrasonic flow measurement for water, coolant, and process liquids.",
      voltage: "24V DC",
      enclosure: "316 stainless steel",
      operatingTemp: "-10C to 70C",
      warranty: "3 years",
    },
    assets: {
      heroImage: imageFor("photo-1581092918056-0c4c3acd3789"),
      detailImage: imageFor("photo-1504917595217-d4dc5ebe6122"),
    },
  },
  {
    id: "LX-900",
    name: "LumaTrack Sensor Bar",
    category: "Optical Sensors",
    thumbnail: imageFor("photo-1555664424-778a1e5e1b48"),
    attributes: {
      productId: "LX-900",
      productName: "LumaTrack Sensor Bar",
      category: "Optical Sensors",
      description: "High speed optical inspection bar for packaging lines and precision sorting.",
      voltage: "12V DC",
      enclosure: "Anodized aluminum",
      operatingTemp: "0C to 50C",
      warranty: "2 years",
    },
    assets: {
      heroImage: imageFor("photo-1516321318423-f06f85e504b3"),
      detailImage: imageFor("photo-1581092162384-8987c1d64718"),
    },
  },
];

export const staticItems = [
  { type: "logo", label: "Primary logo", source: "brand.logo", width: 132, height: 56 },
];

export const defaultTemplates = [
  {
    id: "tpl-a4-technical",
    name: "A4 Product Tech Sheet",
    brandId: "voltedge",
    page: {
      size: "A4",
      orientation: "portrait",
      background: "#ffffff",
      backgroundOpacity: 1,
      edgeStyle: "solid",
      edgeColor: "#bac8c4",
      edgeOpacity: 1,
      edgeWidth: 1,
    },
    pages: [{ id: "sheet-1" }],
    elements: [
      { id: "el-logo", type: "logo", label: "Primary logo", x: 34, y: 28, width: 132, height: 56, mediaWidth: 178, mediaHeight: 76 },
      {
        id: "el-title",
        type: "text",
        label: "Product name",
        binding: "attributes.productName",
        x: 34,
        y: 112,
        width: 330,
        height: 58,
        fontSize: 26,
        color: "#17211f",
        borderColor: "#cbd8d4",
        borderWidth: 0,
        borderRadius: 8,
      },
      {
        id: "el-hero",
        type: "image",
        label: "Hero image",
        binding: "assets.heroImage",
        x: 34,
        y: 194,
        width: 252,
        height: 252,
        mediaWidth: 350,
        mediaHeight: 350,
        borderRadius: 8,
      },
      {
        id: "el-copy",
        type: "text",
        label: "Description",
        binding: "attributes.description",
        x: 316,
        y: 194,
        width: 228,
        height: 100,
        fontSize: 15,
        color: "#17211f",
        borderColor: "#cbd8d4",
        borderWidth: 1,
        borderRadius: 8,
      },
      {
        id: "el-table",
        type: "table",
        label: "Spec table",
        binding: "technicalSpecs",
        x: 316,
        y: 326,
        width: 228,
        height: 178,
        borderColor: "#cbd8d4",
        borderWidth: 1,
        borderRadius: 8,
      },
      {
        id: "el-band",
        type: "shape",
        label: "Footer band",
        x: 0,
        y: 786,
        width: 595,
        height: 56,
        background: "#0c7c78",
        borderColor: "#0c7c78",
        borderWidth: 0,
        borderRadius: 0,
      },
    ],
  },
];
